'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.17929
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強型別資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication6.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強型別資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _55621491201104032112043884947680543_075() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("55621491201104032112043884947680543_075", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property Forest_ruin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forest ruin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property icon36b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon36b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property TOP8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TOP8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property touhou_00023() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("touhou_00023", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property メイベル() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("メイベル", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 愛莉絲() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("愛莉絲", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 愛莉絲的人偶_荷蘭_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("愛莉絲的人偶(荷蘭)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 霧雨_魔理沙() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("霧雨 魔理沙", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
